<a href="https://colab.research.google.com/github/laxmipunnam/AI_ML_BootCamp_Project/blob/main/project%20copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/cmp_placement_dataset.csv')

In [ ]:
df.head()

RegNo  Quants  LogicalReasoning  Verbal  Programming   CGPA  \
0  T150054001      11                11      10           11  10.00   
1  T150054002       8                10      11           18   8.80   
2  T150054003      11                11      10            8   9.63   
3  T150054004      14                13       8            8   6.55   
4  T150054005      10                 7       7           10   7.27   

   Networking  CloudComp  WebServices  DataAnalytics  QualityAssurance   AI  \
0         4.3        6.2          7.4            8.3               8.1  8.0   
1         8.9        8.0          8.0            8.0               8.3  9.4   
2         8.4        8.0          8.0            8.0               8.0  5.4   
3         4.5        6.5          6.9            3.3               4.1  4.6   
4         3.1        5.6          6.7            4.6               2.7  4.4   

   Placed  
0       1  
1       1  
2       1  
3       0  
4       0

In [ ]:
df=df.drop('RegNo',axis=1)

In [ ]:
#load the data
X = df.iloc[:,:-1].values#independent -- message
Y = df.iloc[:,-1:].values #dependent -- label
X

array([[11. , 11. , 10. , ...,  8.3,  8.1,  8. ],
       [ 8. , 10. , 11. , ...,  8. ,  8.3,  9.4],
       [11. , 11. , 10. , ...,  8. ,  8. ,  5.4],
       ...,
       [15. , 14. , 17. , ...,  6.7,  5.9,  5.8],
       [15. , 17. , 16. , ...,  7. ,  6.3,  6.6],
       [20. , 16. , 19. , ...,  6.5,  7.1,  7.3]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=20)

In [ ]:
x_train

array([[ 1.01826926e+00, -1.80467158e-01,  9.32371848e-01, ...,
         1.62498433e+00,  1.49055572e+00,  1.70983796e+00],
       [ 8.14872060e-02, -1.80467158e-01,  2.65521963e-01, ...,
         5.85450046e-01,  5.68627589e-01,  3.03394330e-01],
       [ 3.15682719e-01,  2.67631568e-01,  2.65521963e-01, ...,
         3.90537367e-01,  2.22904541e-01,  3.03394330e-01],
       ...,
       [ 1.01826926e+00,  4.91680932e-01,  2.65521963e-01, ...,
         4.55508260e-01, -6.51979996e-02,  4.51441028e-01],
       [ 5.49878233e-01,  4.35822049e-02,  7.10088553e-01, ...,
        -3.89113348e-01,  4.53386573e-01, -5.10862511e-01],
       [ 8.14872060e-02,  2.67631568e-01,  9.32371848e-01, ...,
         7.12009785e-04, -7.57749148e-03,  3.77417679e-01]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(sc.transform(x_test))
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1])

In [ ]:
print("Predicted value for training data:",classifier.score(x_train,y_train)*100)
print("Predicted value for testing data:",classifier.score(x_test,y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 75.34246575342466


In [ ]:
accuracy=classifier.score(X,Y)*100
print(accuracy)

94.79452054794521
